In [1]:
#Import Libraries
import nltk
import pandas as pd
import re
from textblob import TextBlob

In [2]:
#Read Dataset
data1 = pd.read_csv('edited_d1.csv')
data3 = pd.read_csv('all_hotel_attrs_tripadvisor.csv')

In [3]:
#Lexicon
stopwords = [ "hmm","[","]",'·','·',"...","ok","th","rd","th","nd","!","#","$","%","&","'","’","u","v","b","r","(",")","*","+","-",".","/",":",";","<","=",">","?","@","[","/","]","^","_","`","{","|","}","~",",","a", "about", "above", "after", "again", "against", "all", "am", "an", "and", "any", "are", "as", "at", "be", "because", "been", "before", "being", "below", "between", "both", "but", "by", "could", "did", "do", "does", "doing", "down", "during", "each", "few", "for", "from", "further", "had", "has", "have", "having", "he", "he'd", "he'll", "he's", "her", "here", "here's", "hers", "herself", "him", "himself", "his", "how", "how's", "i", "i'd", "i'll", "i'm", "i've", "if", "in", "into", "is", "it", "it's", "its", "itself", "let's", "me", "more", "most", "my", "myself", "nor", "of", "on", "once", "only", "or", "other", "ought", "our", "ours", "ourselves", "out", "over", "own", "same", "she","please","sorry","bye", "she'd", "she'll", "she's", "should", "so", "some", "such", "than", "that", "that's", "the", "their", "theirs", "them", "themselves", "then", "there", "there's", "these", "they", "they'd", "they'll", "they're", "they've", "this", "those", "through", "to", "too", "under", "until", "up", "very", "was", "we", "we'd", "we'll", "we're", "we've", "were", "what", "what's", "when", "when's", "where", "where's", "which", "while", "who", "who's", "whom", "why", "why's", "with", "would", "you", "you'd", "you'll", "you're", "you've", "your", "yours", "yourself", "yourselves","hello"]

In [4]:
#Hotel Names
name1 = data1['hotel_name']
name3 = data3['hotel_name']
name1  = name1.unique()
name3  = name3.unique()

In [14]:
#Data Structures
Hotel_id = []
Tripadvisor_hotel_id = []
Trip_advisor_rating = []
Composite_rating = []
review_tripadvisor = []
top_positive_features = []
top_negative_features = []
top_talked_about_features = []
Room_type = []
Oldest_review_date = []
latest_review_date = []
common_surrounding_hotels_features = []
Different_surrounding_hotels_words = []
Hotel_neg = []
Hotel_pos = []
Hotel_com = []

for k in range(0,length):
    a = name1[k]
    
    #Details of the hotel
    hotel1 = data1.loc[data1['hotel_name'] ==a]
    hotel3 = data3.loc[data3['hotel_name'] ==a]
    
    #Hotel ID
    hid1 = hotel3['hotel_id']
    hid1 = hid1.iloc[0]
    
    #Hotel Rating 
    r1 = hotel3['rating']
    r1 = r1.iloc[0]
    
    #No of reviews
    re1 = hotel3['no_of_reviews']
    re1 = re1.iloc[0]
    
    #Hotel Review
    re = hotel1['review_title']
    re.append(hotel1['review_content'])
    
    #Drop 'nan' values 
    re = re.dropna()
    re = "".join(re)
    
    #Lower case
    re = re.lower()
    
    #Word Tokenization 
    re = nltk.word_tokenize(re)
    
    #POS Tagger 
    tags3 = nltk.pos_tag(re)
    R=[]
    N=[]
    P=[]
    for t in tags3:
            log = (t[1] == 'NN')
            if log == True:
                R.append(t[0])
    
    #Stopword Removal
    R = [words for words in R if words not in stopwords]
    
    #Sentimental Analysis
    for x in R:
        s = TextBlob(x)
        if s.sentiment.polarity < 0:
            N.append(x)
    for x in R:
        s = TextBlob(x)
        if s.sentiment.polarity > 0:
            P.append(x)
            
    #Counter
    from collections import Counter 
    Counter1 = Counter(N) 
    Counter2 = Counter(P) 
    Counter3 = Counter(R) 
    
    #Most Common Words
    most_occur_n = Counter1.most_common(5) 
    most_occur_p = Counter2.most_common(5)
    most_occur_r = Counter3.most_common(5)
    
    #Review Date
    date = hotel1['review_date']
    date = pd.to_datetime(date, errors='coerce')
    date = date[date.notnull()]
    date = sorted(date)
    dlen = len(date)
    
    #Oldest and Latest Review Date
    if(dlen!=0):
        old = date[0]
        new = date[dlen-1]
        old  = old.date()
        new = new.date()
        from datetime import datetime
        old = old.strftime("%d/%m/%Y")
        new = new.strftime("%d/%m/%Y")
    else:
        old = 'None'
        new = 'None'
        
    #Top most positive features
    #Top most negative features
    #Top most talked about features
    Hotel_neg = []
    Hotel_pos = []
    Hotel_com = []
    Hotel_neg.append(most_occur_n)
    Hotel_pos.append(most_occur_p)
    Hotel_com.append(most_occur_r)
    
    #Hotel Facilities/Features
    cf = hotel3['facilities']
    cf = cf.iloc[0]
    
    #Final Columns 
    Hotel_id.append(k+1)
    Tripadvisor_hotel_id.append(hid1)
    Trip_advisor_rating.append(r1)
    review_tripadvisor.append(re1)
    top_positive_features.append(Hotel_pos)
    top_negative_features.append(Hotel_neg)
    top_talked_about_features.append(Hotel_com)
    Oldest_review_date.append(old)
    latest_review_date.append(new)
    common_surrounding_hotels_features.append(cf)
    Composite_rating.append(c)

In [15]:
#DataFrame Creation 
data = {'Hotel_id':Hotel_id,'Tripadvisor_hotel_id':Tripadvisor_hotel_id,'Trip_advisor_rating':Trip_advisor_rating, 'review_tripadvisor':review_tripadvisor,'top_positive_features':top_positive_features, 'top_negative_features':top_negative_features, 'top_talked_about_features':top_talked_about_features,"Oldest_review_date":Oldest_review_date,'latest_review_date':latest_review_date, "common_surrounding_hotels_features":common_surrounding_hotels_features} 
data = pd.DataFrame(data)
data

,Hotel_id,Tripadvisor_hotel_id,Trip_advisor_rating,review_tripadvisor,top_positive_features,top_negative_features,top_talked_about_features,Oldest_review_date,latest_review_date,common_surrounding_hotels_features
0,1,property_636140,4.5,"1,415 reviews","[[(nice, 2)]]",[[]],"[[(hotel, 13), (location, 10), (stay, 9), (hom...",01/07/2018,01/05/2019,"['Pool', 'Free parking', 'Fitness Center with ..."
1,2,property_12918864,4.5,135 reviews,"[[(excellent, 1), (pleasant, 1)]]","[[(dirty, 1)]]","[[(hotel, 11), (service, 5), (burj, 5), (place...",01/09/2017,01/05/2019,"['Pool', 'Free parking', 'Restaurant', 'Free H..."
2,3,property_302457,4.5,"5,631 reviews",[[]],"[[(half, 1)]]","[[(hotel, 5), (al, 5), (luxury, 4), (service, ...",01/04/2019,01/05/2019,"['Pool', 'Room service', 'Restaurant', 'Free H..."
3,4,property_9704275,4.5,"2,262 reviews",[[]],[[]],"[[(hotel, 25), (stay, 12), (dubai, 10), (staff...",01/04/2019,01/05/2019,"['Pool', 'Room service', 'Free parking', 'Rest..."
4,5,property_674662,4,621 reviews,"[[(superb, 1), (okay, 1)]]",[[]],"[[(location, 13), (hotel, 9), (stay, 6), (serv...",01/04/2017,01/05/2019,"['Pool', 'Room service', 'Restaurant', 'Fitnes..."
...,...,...,...,...,...,...,...,...,...,...
2893,2894,property_1015046,4.5,"7,668 reviews","[[(perfect, 1), (fantastic, 1)]]",[[]],"[[(hotel, 12), (stay, 9), (family, 5), (time, ...",01/05/2019,01/05/2019,"['Restaurant', 'Bar/Lounge', 'Room service', '..."
2894,2895,property_15741916,5,81 reviews,"[[(beautiful, 1)]]",[[]],"[[(hotel, 11), (plaza, 5), (place, 4), (servic...",01/03/2019,01/05/2019,"['Pool', 'Room service', 'Free parking', 'Rest..."
2895,2896,property_5667617,4,"1,606 reviews","[[(excellent, 1)]]","[[(center, 1)]]","[[(hotel, 12), (business, 4), (service, 3), (l...",01/04/2018,01/05/2019,"['Pool', 'Room service', 'Free parking', 'Rest..."
2896,2897,property_739160,4.5,192 reviews,"[[(excellent, 1), (superb, 1)]]","[[(toilet, 1), (center, 1)]]","[[(place, 8), (location, 6), (service, 5), (st...",01/05/2016,01/05/2019,"['Pool', 'Fitness Center with Gym / Workout Ro..."
2897,2898,property_3291088,4,444 reviews,"[[(right, 1)]]",[[]],"[[(hotel, 8), (stay, 6), (location, 6), (place...",01/03/2016,01/04/2019,"['Pool', 'Free parking', 'Fitness Center with ..."

In [16]:
#Saving as CSV File 
data.to_csv('Only_Tripadvisor_Summary.csv')