In [3]:
#Import Libraries
import numpy as np
import nltk
import pandas as pd
import re
from textblob import TextBlob
from sklearn import preprocessing

In [3]:
#Read Dataset
data1 = pd.read_csv('Hotelscombined_com.csv',encoding='latin1')
data1

,Hotel_name,Hotel_address,Hotel_ratings,Hotel_price,Hotel_facilities,Review
0,Golden Dreams,"Patnem Beach, South Goa, Chauri, Goa, 403702, ...",Very good 8.4,"Rs1,870",Parking available,Nice huts close to beach. Had a great stay wit...
1,Holiday Inn Resort Goa,"Mobor Beach Cavelossim, Cavelossim, Goa, 403 7...",Fabulous 8.6,"Rs8,299",Free parking,It was a terrible experience though the food a...
2,Novotel Goa Resort and Spa,"Pinto Waddo, Off Main Candolim Road, Candolim,...",Good 7.8,"Rs8,099",Free parking,YOUR SERVICE WAS EXTREMELY GREAT IT WAS UN FOR...
3,Candolim Grande,"Candolim calungute main road, House number 101...",NaN,"Rs3,325",Free parking,NaN
4,"Taj Exotica Resort & Spa, Goa","Calwaddo Benaulim, Benaulim, Goa, 403716, India",Exceptional 9.8,NaN,Free parking,Pinnacle of Hospitality... brilliant property...
...,...,...,...,...,...,...
204,The AGATE Pattaya Boutique Resort,"413/93-96 Moo 12, Jomtien Sai 2 Road, Nongprue...",Fabulous 8.6,NaN,71 guestrooms Near the beach Restaurant and ba...,"Rooms were clean, comfortable. Very friendly s..."
205,I-Talay Resort Pattaya,"30/2 Moo 12, Soi Jomtien 14, Nongprue, Banglam...",Good 6.2,"Rs1,870",45 smoke-free guestrooms Outdoor pool Breakfas...,That smell from the resort was bad The pool lo...
206,COSI Pattaya Wong Amat Beach,"157/535 Moo 5, Naklua, Banglamung, Pattaya, Ch...",Exceptional 9.4,"Rs3,168",275 guestrooms Near the beach Outdoor pool Cof...,Great hotel and the staff are friendly. Hotel ...
207,InterContinental Pattaya Resort,"437 Phra Tamnak Road, Pattaya, Chonburi, 20150...",Superb 9.2,"Rs15,754",156 smoke-free guestrooms On a private beach 2...,The service is amazing. I took 4 months twin b...
208,Intimate Hotel Pattaya,"397/42 Moo 10 Soi 14, South Pattaya 2nd, Patta...",Very good 8.2,"Rs3,570",82 guestrooms Near the beach Restaurant and ba...,NaN

In [4]:
#Normalize Ratings
r1 = data1['Hotel_ratings']
r1 = r1.str.extract('(\d+)')
min_max_scaler = preprocessing.MinMaxScaler()
r1_scaled = min_max_scaler.fit_transform(r1)

In [545]:
#Reviews
re1 = data1['Review']

In [546]:
#Lexicon
stopwords = [ "hmm","[","]",'Â·','Â·',"...","ok","th","rd","th","nd","!","#","$","%","&","'","â€™","u","v","b","r","(",")","*","+","-",".","/",":",";","<","=",">","?","@","[","/","]","^","_","`","{","|","}","~",",","a", "about", "above", "after", "again", "against", "all", "am", "an", "and", "any", "are", "as", "at", "be", "because", "been", "before", "being", "below", "between", "both", "but", "by", "could", "did", "do", "does", "doing", "down", "during", "each", "few", "for", "from", "further", "had", "has", "have", "having", "he", "he'd", "he'll", "he's", "her", "here", "here's", "hers", "herself", "him", "himself", "his", "how", "how's", "i", "i'd", "i'll", "i'm", "i've", "if", "in", "into", "is", "it", "it's", "its", "itself", "let's", "me", "more", "most", "my", "myself", "nor", "of", "on", "once", "only", "or", "other", "ought", "our", "ours", "ourselves", "out", "over", "own", "same", "she","please","sorry","bye", "she'd", "she'll", "she's", "should", "so", "some", "such", "than", "that", "that's", "the", "their", "theirs", "them", "themselves", "then", "there", "there's", "these", "they", "they'd", "they'll", "they're", "they've", "this", "those", "through", "to", "too", "under", "until", "up", "very", "was", "we", "we'd", "we'll", "we're", "we've", "were", "what", "what's", "when", "when's", "where", "where's", "which", "while", "who", "who's", "whom", "why", "why's", 'nan',"with", "would", "you", "you'd", "you'll", "you're", "you've", "your", "yours", "yourself", "yourselves","hello"]

In [547]:
#Data Structures
Hotel_neg = []
Hotel_pos = []
Hotel_neu = []
for re in re1:
    re = str(re)
    
    #Lower Case
    re = re.lower()
    
    #Word Tokenization
    re = nltk.word_tokenize(re)
    
    #POS Tagger
    tags3 = nltk.pos_tag(re)
    R=[]
    N=[]
    P=[]
    for t in tags3:
            log = (t[1] == 'NN')
            if log == True:
                R.append(t[0])
                
    #Stopword Removal
    R = [words for words in R if words not in stopwords]
    
    #Sentimental Analysis
    for x in R:
        s = TextBlob(x)
        if s.sentiment.polarity < 0:
            N.append(x)
    for x in R:
        s = TextBlob(x)
        if s.sentiment.polarity > 0:
            P.append(x)
            
    #Counter
    #Top most positive features
    #Top most negative features
    #Top most talked about features
    from collections import Counter 
    Counter1 = Counter(N) 
    Counter2 = Counter(P) 
    Counter3 = Counter(R) 
    
    #Most Common Words
    most_occur_n = Counter1.most_common(5) 
    most_occur_p = Counter2.most_common(5)
    most_occur_r = Counter3.most_common(5)
    
    #Final Columns 
    Hotel_neg.append(str(most_occur_n))
    Hotel_pos.append(str(most_occur_p))
    Hotel_neu.append(str(most_occur_r))

In [5]:
#Data Structures
Com= []
Diff = []
Comx=[]
Diffx= []

#Hotel Cities
Cities = data2['Hotel_city']
Cities = Cities.unique()

for c in Cities:
    
    #Hotels of each city 
    data = data2[data2['Hotel_city'].str.contains(c)] 
    c = c.lower()
    data = data.append(data2[data2['Hotel_city'].str.contains(c)], ignore_index=True )
    
    #Hotel names
    name = data['Hotel_name']
    
    com = []
    dif = []
    
    for n in name:
        
        #Hotel facilities/features
        datas = data[data['Hotel_name']!=n]
        fac = datas['Hotel_facilities']
        fn = data[data['Hotel_name']==n]
        fn = fn['Hotel_facilities']
        fn = fn.iloc[0]
        fn = str(fn)
        fn = fn.lower()
        fn = fn.lower()
        fn = fn.split(',')
        fn = list(fn)
        Facs = []
        for f in fac:
            f = str(f)
            f = f.lower()
            f = f.split(',')
            Facs.append(f)
        Facs = np.array(Facs)
        Facs = np.unique(Facs)
        
        #Common Features with surrounding hotels
        com = [words for words in Facs if words in fn ]
        
        #Different Features from surrounding hotels
        diff = [words for words in Facs if words not in fn ]
        s = []
        w = []
        for g in fn:
            for k in Facs:
                    for l in k:
                        if g==l:
                            if g not in s:
                                s.append(g)
        for g in fn:
            t=0
            for k in Facs:
                for l in k:
                    if g==l:
                        t=1
            if t!=1:
                w.append(g)
        s = str(s)
        w = str(w)
        
        #Final Columns 
        Comx.append(s)
        Diffx.append(w)      
        Com.append(com)
        Diff.append(diff)

In [571]:
#DataFrame Creation
p = pd.DataFrame(Diffs)
q = pd.DataFrame(r1_scaled)
r = pd.DataFrame(Coms)
s=pd.DataFrame(r1_scaled)
t=pd.DataFrame(Hotel_neg)
u=pd.DataFrame(Hotel_neu)
v=pd.DataFrame(Hotel_pos)
Data1 = pd.concat([q,s,v,t,u,r,p],axis=1)
Data1

,0,0,0,0,0,0,0
0,0.750,0.750,[],[],"[('beach', 1), ('stay', 1), ('family', 1), ('p...",['parking'],['available']
1,0.750,0.750,[],[],"[('experience', 2), ('food', 1), ('restaurant'...","['free', 'parking']",[]
2,0.625,0.625,[],[],"[('service', 2), ('experience', 2), ('time', 1...","['free', 'parking']",[]
3,NaN,NaN,[],[],[],"['free', 'parking']",[]
4,0.875,0.875,[],[],"[('pinnacle', 1), ('hospitality', 1), ('proper...","['free', 'parking']",[]
...,...,...,...,...,...,...,...
204,0.750,0.750,[],[],"[('staff', 1), ('breakfast', 1), ('spread', 1)...","['guestrooms', 'near', 'the', 'beach', '4', 'r...","['567', 'wifi', 'lobby']"
205,0.500,0.500,"[('smile', 1)]",[],"[('resort', 2), ('area', 2), ('smell', 1), ('p...","['smoke-free', 'guestrooms', 'on', 'the', 'bea...","['555', '5', 'bars/lounges', 'lazy', 'river', ..."
206,0.875,0.875,[],[],"[('hotel', 2), ('staff', 1), ('location', 1)]","['guestrooms', 'restaurant', 'and', 'bar/loung...","['269', 'gift', 'shops/newsstands', 'tour/tick..."
207,0.875,0.875,[],[],"[('sterilizer', 2), ('service', 1), ('baby', 1...","['guestrooms', 'near', 'the', 'beach', 'restau...",['71']
208,0.750,0.750,[],[],[],"['smoke-free', 'guestrooms', 'outdoor', 'pool'...",['45']

In [572]:
#Assigning DataFrame Columns 
Data1.columns = ['Hotels_combined_rating','Composite_rating','top_positive_features','top_negative_features','top_talked_about_features','common_surrounding_hotels_features','different_surrounding_hotels_features']
Data1

,Hotels_com_rating,Composite_rating,top_positive_features,top_negative_features,top_talked_about_features,common_surrounding_hotels_features,different_surrounding_hotels_features
0,0.750,0.750,[],[],"[('beach', 1), ('stay', 1), ('family', 1), ('p...",['parking'],['available']
1,0.750,0.750,[],[],"[('experience', 2), ('food', 1), ('restaurant'...","['free', 'parking']",[]
2,0.625,0.625,[],[],"[('service', 2), ('experience', 2), ('time', 1...","['free', 'parking']",[]
3,NaN,NaN,[],[],[],"['free', 'parking']",[]
4,0.875,0.875,[],[],"[('pinnacle', 1), ('hospitality', 1), ('proper...","['free', 'parking']",[]
...,...,...,...,...,...,...,...
204,0.750,0.750,[],[],"[('staff', 1), ('breakfast', 1), ('spread', 1)...","['guestrooms', 'near', 'the', 'beach', '4', 'r...","['567', 'wifi', 'lobby']"
205,0.500,0.500,"[('smile', 1)]",[],"[('resort', 2), ('area', 2), ('smell', 1), ('p...","['smoke-free', 'guestrooms', 'on', 'the', 'bea...","['555', '5', 'bars/lounges', 'lazy', 'river', ..."
206,0.875,0.875,[],[],"[('hotel', 2), ('staff', 1), ('location', 1)]","['guestrooms', 'restaurant', 'and', 'bar/loung...","['269', 'gift', 'shops/newsstands', 'tour/tick..."
207,0.875,0.875,[],[],"[('sterilizer', 2), ('service', 1), ('baby', 1...","['guestrooms', 'near', 'the', 'beach', 'restau...",['71']
208,0.750,0.750,[],[],[],"['smoke-free', 'guestrooms', 'outdoor', 'pool'...",['45']

In [573]:
#Saving as CSV File
Data1.to_csv('Hotelscombined_com_Summary.csv')