In [1]:
#Import Libraries
import nltk
import pandas as pd
from sklearn import preprocessing

In [4]:
#Read dataset
d1 = pd.read_csv('all_hotel_attrs_bookingcom.csv')
d2 = pd.read_csv('all_hotel_attrs_tripadvisor.csv')

In [448]:
t=d1['rating']
c=0
for i in t:
    if i=='Number 63':
        print(i)
        print(c)
        d1=d1.drop(d1.index[c])
    c=c+1

Number 63
297919

In [5]:
d1
x = d1[['rating']].values.astype(float)
min_max_scaler = preprocessing.MinMaxScaler()
x_scaled = min_max_scaler.fit_transform(x)

In [6]:
s=pd.DataFrame(x_scaled)
d1['rating']=s
d1

,hotel_id,hotel_city,hotel_name,hotel_address,loc_coordinates,facilities,room_types,no of reviews,rating,rating class,Other_ratings,hotel_type
0,show_id294936,London,Princes Gardens,"Imperial College London, Prince's Garden, Watt...","51.49864990,-0.17341465","['Free WiFi Internet Access Included', 'Parkin...","['Single Room', 'Double Room', 'Twin Room']","5,298 reviews",0.746667,Very good,"{'Staff': '8.0', 'Facilities': '7.4', 'Cleanli...",Student accommodation
1,show_id3690340,London,Beautiful Notting Hill Garden Apartment,"61B Cornwall Crescent, Kensington and Chelsea,...","51.51423600,-0.21119675","['Free WiFi Internet Access Included', 'Non Sm...",['Apartment'],8 reviews,0.933333,Exceptional,"{'Staff\xa0': '10', 'Facilities\xa0': '9.7', '...",Apartment
2,show_id4916754,London,"Boutique 2 Bed in Notting Hill, Westbourne Park","19 Aldridge Road Villas Flat 4, Westminster Bo...","51.51918640,-0.20014320","['Family Rooms', 'Heating']",['Two-Bedroom Apartment'],NaN,NaN,NaN,NaN,Apartment
3,show_id5048582,London,-30% NATURAL HISTORY MUSEUM LUXURY APARTMENT,"53 Queen's Gate apartment 4, Kensington and Ch...","51.49640050,-0.17960130","['Free WiFi Internet Access Included', 'Family...",['Two-Bedroom Apartment'],NaN,NaN,NaN,NaN,Apartment
4,show_id4173097,London,The Lovely Longridge Road Apartment,"Longridge Road, Kensington and Chelsea, London...","51.49262000,-0.19841000","['Free WiFi Internet Access Included', 'Heating']",['Studio Apartment'],NaN,NaN,NaN,NaN,Apartment
...,...,...,...,...,...,...,...,...,...,...,...,...
5877,show_id2995477,Manila,Frank Lloyd Apartelle,"Frank Lloyd Mansion Building, Meekness Extensi...","14.48928831,121.01532054",['Free WiFi Internet Access Included'],"['Studio Apartment', 'Studio Apartment', 'Stud...",517 reviews,0.866667,Superb,"{'Staff\xa0': '9.7', 'Facilities': '8.6', 'Cle...",Apartment
5878,show_id2222765,Manila,Marites Apartments,"Shell Residences, EDSA corner Sunrise Drive, P...","14.53649887,120.98301172","['Free WiFi Internet Access Included', 'Swimmi...","['Apartment with Balcony', 'Apartment with Bal...",493 reviews,0.800000,Very good,"{'Staff': '8.4', 'Facilities': '8.2', 'Cleanli...",Apartment
5879,show_id4452923,Manila,"Carlos P Garcia, C5 Ave.","Carlos P Garcia, C5 Ave. Ridgewood Towers, 163...","14.54116713,121.05505518","['Free WiFi Internet Access Included', 'Swimmi...",['Two-Bedroom Apartment'],NaN,NaN,NaN,NaN,Apartment
5880,show_id1338347,Manila,Novotel Manila Araneta Center,"General Aguinaldo Avenue, Araneta Center, Cuba...","14.62015498,121.05401539","['Free WiFi Internet Access Included', 'Swimmi...","['Deluxe King Room', 'Executive King Room', 'S...","1,765 reviews",0.853333,Fabulous,"{'Staff': '8.9', 'Facilities\xa0': '9.0', 'Cle...",Hotel
5881,show_id3684842,Manila,Loft at Eton Residences beside Greenbelt by Pr...,"122 Legazpi Street, Makati, 1229 Manila, Phili...","14.55391700,121.02032700","['Free WiFi Internet Access Included', 'Swimmi...",['Apartment'],11 reviews,0.666667,Good,"{'Staff': '8.0', 'Facilities': '6.8', 'Cleanli...",Apartment

In [7]:
d1["hotel_id"] = d1["hotel_id"].str.replace("show_id","")
d1

,hotel_id,hotel_city,hotel_name,hotel_address,loc_coordinates,facilities,room_types,no of reviews,rating,rating class,Other_ratings,hotel_type
0,294936,London,Princes Gardens,"Imperial College London, Prince's Garden, Watt...","51.49864990,-0.17341465","['Free WiFi Internet Access Included', 'Parkin...","['Single Room', 'Double Room', 'Twin Room']","5,298 reviews",0.746667,Very good,"{'Staff': '8.0', 'Facilities': '7.4', 'Cleanli...",Student accommodation
1,3690340,London,Beautiful Notting Hill Garden Apartment,"61B Cornwall Crescent, Kensington and Chelsea,...","51.51423600,-0.21119675","['Free WiFi Internet Access Included', 'Non Sm...",['Apartment'],8 reviews,0.933333,Exceptional,"{'Staff\xa0': '10', 'Facilities\xa0': '9.7', '...",Apartment
2,4916754,London,"Boutique 2 Bed in Notting Hill, Westbourne Park","19 Aldridge Road Villas Flat 4, Westminster Bo...","51.51918640,-0.20014320","['Family Rooms', 'Heating']",['Two-Bedroom Apartment'],NaN,NaN,NaN,NaN,Apartment
3,5048582,London,-30% NATURAL HISTORY MUSEUM LUXURY APARTMENT,"53 Queen's Gate apartment 4, Kensington and Ch...","51.49640050,-0.17960130","['Free WiFi Internet Access Included', 'Family...",['Two-Bedroom Apartment'],NaN,NaN,NaN,NaN,Apartment
4,4173097,London,The Lovely Longridge Road Apartment,"Longridge Road, Kensington and Chelsea, London...","51.49262000,-0.19841000","['Free WiFi Internet Access Included', 'Heating']",['Studio Apartment'],NaN,NaN,NaN,NaN,Apartment
...,...,...,...,...,...,...,...,...,...,...,...,...
5877,2995477,Manila,Frank Lloyd Apartelle,"Frank Lloyd Mansion Building, Meekness Extensi...","14.48928831,121.01532054",['Free WiFi Internet Access Included'],"['Studio Apartment', 'Studio Apartment', 'Stud...",517 reviews,0.866667,Superb,"{'Staff\xa0': '9.7', 'Facilities': '8.6', 'Cle...",Apartment
5878,2222765,Manila,Marites Apartments,"Shell Residences, EDSA corner Sunrise Drive, P...","14.53649887,120.98301172","['Free WiFi Internet Access Included', 'Swimmi...","['Apartment with Balcony', 'Apartment with Bal...",493 reviews,0.800000,Very good,"{'Staff': '8.4', 'Facilities': '8.2', 'Cleanli...",Apartment
5879,4452923,Manila,"Carlos P Garcia, C5 Ave.","Carlos P Garcia, C5 Ave. Ridgewood Towers, 163...","14.54116713,121.05505518","['Free WiFi Internet Access Included', 'Swimmi...",['Two-Bedroom Apartment'],NaN,NaN,NaN,NaN,Apartment
5880,1338347,Manila,Novotel Manila Araneta Center,"General Aguinaldo Avenue, Araneta Center, Cuba...","14.62015498,121.05401539","['Free WiFi Internet Access Included', 'Swimmi...","['Deluxe King Room', 'Executive King Room', 'S...","1,765 reviews",0.853333,Fabulous,"{'Staff': '8.9', 'Facilities\xa0': '9.0', 'Cle...",Hotel
5881,3684842,Manila,Loft at Eton Residences beside Greenbelt by Pr...,"122 Legazpi Street, Makati, 1229 Manila, Phili...","14.55391700,121.02032700","['Free WiFi Internet Access Included', 'Swimmi...",['Apartment'],11 reviews,0.666667,Good,"{'Staff': '8.0', 'Facilities': '6.8', 'Cleanli...",Apartment

In [8]:
d1.to_csv('edited_d1_attr.csv')

In [378]:
d2copy=d2

In [10]:
t=d2['rating']
c=0
for i in t:
    if i=='#173':
        print(i)
        print(c)
        d2=d2.drop(d2.index[c])
    c=c+1

#173
5698

In [11]:
y = d2[['rating']].values.astype(float)
min_max_scaler = preprocessing.MinMaxScaler()
y_scaled = min_max_scaler.fit_transform(y)

In [12]:
S=pd.DataFrame(y_scaled)
d2['rating']=S
d2

,hotel_id,hotel_city,hotel_name,hotel_address,location,facilities,number_of_rooms,price_range,no_of_reviews,rank,rating,rating_class,other_ratings,also_known_as,formerly_known_as
0,property_1657415,London,Park Plaza Westminster Bridge London,"200 Westminster Bridge Road, London SE1 7UT, E...",United KingdomEnglandLondonSouthbank,"['Room service', 'Free Internet', 'Restaurant'...",1019,$207 - $520 (Based on Average Rates for a Stan...,"20,864 reviews",#309,0.9,Excellent,"{'Location': 5.0, 'Cleanliness': 4.5, 'Service...",park plaza westminster bridge london hotel london,NaN
1,property_193143,London,Park Grand London Kensington,"33-37 Hogarth Road | Kensington, London SW5 0Q...",United KingdomEnglandLondonEarls CourtSouth Ke...,"['Room service', 'Restaurant', 'Fitness Center...",133,$159 - $356 (Based on Average Rates for a Stan...,"4,306 reviews",#34,0.9,Excellent,"{'Location': 4.5, 'Cleanliness': 4.5, 'Service...",best western premier shaftsbury london kensing...,BEST WESTERN PREMIER Park Grand London Kensington
2,property_193097,London,The Tower Hotel,"St Katharine's Way, London E1W 1LD, England",United KingdomEnglandLondon,"['Restaurant', 'Room service', 'Free High Spee...",801,$125 - $332 (Based on Average Rates for a Stan...,"9,370 reviews",#394,0.8,Very good,"{'Location': 4.5, 'Cleanliness': 4.0, 'Service...",the tower hotel londonthe tower londonhotel th...,NaN
3,property_243430,London,London House Hotel,"81 Kensington Gardens Square | Bayswater, Lond...",United KingdomEnglandLondonNotting Hill,"['Free High Speed Internet (WiFi)', 'Breakfast...",103,$119 - $266 (Based on Average Rates for a Stan...,"2,733 reviews",#345,0.8,Very good,"{'Location': 4.5, 'Cleanliness': 4.5, 'Service...",london house hotellondon hotel,NaN
4,property_13474415,London,Z Hotel Tottenham Court Road,"52 Poland Street, London W1F 7NQ, England",United KingdomEnglandLondonSoho,"['Free High Speed Internet (WiFi)', 'Concierge...",120,$120 - $312 (Based on Average Rates for a Stan...,111 reviews,#389,0.9,Excellent,"{'Location': 5.0, 'Cleanliness': 5.0, 'Service...",NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10013,property_2525982,Manila,Bukingham Pension,"General Malvar St, Malate, Manila, Luzon, Phil...",PhilippinesLuzonMetro ManilaManila,[],NaN,NaN,NaN,NaN,NaN,NaN,{},NaN,NaN
10014,property_3786493,Manila,Butiki Planet,"CRL Building, Parkhomes, Tunasan, Manila, Luzo...",PhilippinesLuzonMetro ManilaManila,[],2,NaN,NaN,NaN,NaN,NaN,{},NaN,NaN
10015,property_6946138,Manila,Casablanca Manila Guest House,"11-A and 15-A Escarlata Street, Manila, Luzon,...",PhilippinesLuzonMetro ManilaManila,[],2,NaN,NaN,NaN,NaN,NaN,{},NaN,NaN
10016,property_1197748,Manila,Center Point Hotel,"1430 A. Mabini st. Ermita, Manila, Luzon, Phil...",PhilippinesLuzonMetro ManilaManila,[],257,NaN,NaN,NaN,NaN,NaN,{},NaN,NaN
10017,property_13101457,Manila,Cityplace Residences,"758 Juan Luna Street, Manila, Luzon 1006, Phil...",PhilippinesLuzonMetro ManilaManila,[],NaN,NaN,NaN,NaN,NaN,NaN,{},NaN,NaN

In [13]:
d2["hotel_id"] = d2["hotel_id"].str.replace("property_","")
d2

,hotel_id,hotel_city,hotel_name,hotel_address,location,facilities,number_of_rooms,price_range,no_of_reviews,rank,rating,rating_class,other_ratings,also_known_as,formerly_known_as
0,1657415,London,Park Plaza Westminster Bridge London,"200 Westminster Bridge Road, London SE1 7UT, E...",United KingdomEnglandLondonSouthbank,"['Room service', 'Free Internet', 'Restaurant'...",1019,$207 - $520 (Based on Average Rates for a Stan...,"20,864 reviews",#309,0.9,Excellent,"{'Location': 5.0, 'Cleanliness': 4.5, 'Service...",park plaza westminster bridge london hotel london,NaN
1,193143,London,Park Grand London Kensington,"33-37 Hogarth Road | Kensington, London SW5 0Q...",United KingdomEnglandLondonEarls CourtSouth Ke...,"['Room service', 'Restaurant', 'Fitness Center...",133,$159 - $356 (Based on Average Rates for a Stan...,"4,306 reviews",#34,0.9,Excellent,"{'Location': 4.5, 'Cleanliness': 4.5, 'Service...",best western premier shaftsbury london kensing...,BEST WESTERN PREMIER Park Grand London Kensington
2,193097,London,The Tower Hotel,"St Katharine's Way, London E1W 1LD, England",United KingdomEnglandLondon,"['Restaurant', 'Room service', 'Free High Spee...",801,$125 - $332 (Based on Average Rates for a Stan...,"9,370 reviews",#394,0.8,Very good,"{'Location': 4.5, 'Cleanliness': 4.0, 'Service...",the tower hotel londonthe tower londonhotel th...,NaN
3,243430,London,London House Hotel,"81 Kensington Gardens Square | Bayswater, Lond...",United KingdomEnglandLondonNotting Hill,"['Free High Speed Internet (WiFi)', 'Breakfast...",103,$119 - $266 (Based on Average Rates for a Stan...,"2,733 reviews",#345,0.8,Very good,"{'Location': 4.5, 'Cleanliness': 4.5, 'Service...",london house hotellondon hotel,NaN
4,13474415,London,Z Hotel Tottenham Court Road,"52 Poland Street, London W1F 7NQ, England",United KingdomEnglandLondonSoho,"['Free High Speed Internet (WiFi)', 'Concierge...",120,$120 - $312 (Based on Average Rates for a Stan...,111 reviews,#389,0.9,Excellent,"{'Location': 5.0, 'Cleanliness': 5.0, 'Service...",NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10013,2525982,Manila,Bukingham Pension,"General Malvar St, Malate, Manila, Luzon, Phil...",PhilippinesLuzonMetro ManilaManila,[],NaN,NaN,NaN,NaN,NaN,NaN,{},NaN,NaN
10014,3786493,Manila,Butiki Planet,"CRL Building, Parkhomes, Tunasan, Manila, Luzo...",PhilippinesLuzonMetro ManilaManila,[],2,NaN,NaN,NaN,NaN,NaN,{},NaN,NaN
10015,6946138,Manila,Casablanca Manila Guest House,"11-A and 15-A Escarlata Street, Manila, Luzon,...",PhilippinesLuzonMetro ManilaManila,[],2,NaN,NaN,NaN,NaN,NaN,{},NaN,NaN
10016,1197748,Manila,Center Point Hotel,"1430 A. Mabini st. Ermita, Manila, Luzon, Phil...",PhilippinesLuzonMetro ManilaManila,[],257,NaN,NaN,NaN,NaN,NaN,{},NaN,NaN
10017,13101457,Manila,Cityplace Residences,"758 Juan Luna Street, Manila, Luzon 1006, Phil...",PhilippinesLuzonMetro ManilaManila,[],NaN,NaN,NaN,NaN,NaN,NaN,{},NaN,NaN

In [14]:
d2.to_csv('edited_d2_attr.csv')

In [18]:
data_attr = d1.merge(d2, on='hotel_name', how='inner')
data_attr

,hotel_id_x,hotel_city_x,hotel_name,hotel_address_x,loc_coordinates,facilities_x,room_types,no of reviews,rating_x,rating class,...,facilities_y,number_of_rooms,price_range,no_of_reviews,rank,rating_y,rating_class,other_ratings,also_known_as,formerly_known_as
0,188272,Dubai,Premier Inn Dubai Investments Park,"Dubai Investment Park, Dubai Investment Park, ...","25.00816035,55.15673965","['Free WiFi Internet Access Included', 'Swimmi...","['Double Room - Non Smoking', 'Twin Room - Non...","2,145 reviews",0.773333,Very good,...,"['Restaurant', 'Free parking', 'Pool', 'Free H...",304,$33 - $121 (Based on Average Rates for a Stand...,"1,614 reviews",#84,0.9,Excellent,"{'Location': 3.5, 'Cleanliness': 4.5, 'Service...",premier inn dubai investments park hotel dubai,NaN
1,67267,Dubai,Vida Downtown,"Sheikh Mohammed Bin Rashid Boulevard, Downtown...","25.19001034,55.27451277","['Free WiFi Internet Access Included', 'Swimmi...","['Deluxe Room', 'Deluxe Pool View Room', 'Delu...","1,998 reviews",0.813333,Fabulous,...,"['Pool', 'Fitness Center with Gym / Workout Ro...",156,$121 - $316 (Based on Average Rates for a Stan...,"3,068 reviews",#48,0.9,Excellent,"{'Location': 5.0, 'Cleanliness': 5.0, 'Service...",qamardeen hotel dubai,NaN
2,3876254,Mussoorie,City Heart - A Comfortable Stay,":Omkaranand social palace bus stand , 249201 M...","30.10532416,78.29139876","['Free Parking', 'Family Rooms', 'Airport Shut...","['Budget Double Room', 'Deluxe Double Room']",NaN,NaN,NaN,...,[],NaN,$18 - $23 (Based on Average Rates for a Standa...,NaN,NaN,NaN,NaN,{},NaN,NaN
3,3613609,Dubai,Stella Di Mare Dubai Marina Hotel,"Al Mattla'ee Street Dubai Marina, Dubai Marina...","25.06874200,55.13404300","['Free WiFi Internet Access Included', 'Swimmi...","['Deluxe King Room City View', 'Deluxe Twin Ro...",931 reviews,0.813333,Fabulous,...,"['Pool', 'Room service', 'Restaurant', 'Bar/Lo...",369,$77 - $217 (Based on Average Rates for a Stand...,128 reviews,#175,0.9,Excellent,"{'Location': 4.5, 'Cleanliness': 4.5, 'Service...",NaN,NaN
4,266400,Dubai,Park Regis Kris Kin Hotel,Sheikh Khalifah Bin Zayed St. Opp Burjuman Cen...,"25.25230427,55.30323118","['Free WiFi Internet Access Included', 'Swimmi...","['Deluxe Double Room', 'Superior Double Room',...","3,187 reviews",0.760000,Very good,...,"['Pool', 'Free High Speed Internet (WiFi)', 'F...",384,$57 - $170 (Based on Average Rates for a Stand...,"2,167 reviews",#222,0.8,Very good,"{'Location': 4.0, 'Cleanliness': 4.5, 'Service...",NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1169,2411411,Manila,Go Hotels Ermita,"1412 A. Mabini St. Ermita, Ermita, 1004 Manila...","14.57572089,120.98216383","['Free WiFi Internet Access Included', 'Airpor...","['Queen or Twin Room', 'Standard Queen Room']",560 reviews,0.706667,Good,...,"['Free High Speed Internet (WiFi)', 'Laundry S...",219,$27 - $43 (Based on Average Rates for a Standa...,28 reviews,#14,0.7,Very good,"{'Location': 4.0, 'Cleanliness': 4.5, 'Service...",NaN,NaN
1170,237290,Manila,Sofitel Philippine Plaza Manila,"CCP Complex, Roxas Boulevard, Pasay, 1300 Mani...","14.55306002,120.98064601","['Free WiFi Internet Access Included', 'Swimmi...","['Superior Twin Room with City View', 'Superio...","2,326 reviews",0.773333,Very good,...,"['Restaurant', 'Room service', 'Fitness Center...",609,$106 - $237 (Based on Average Rates for a Stan...,"5,848 reviews",#7,0.8,Very good,"{'Location': 4.0, 'Cleanliness': 4.5, 'Service...",philippine travelsofitel manilaaccor philippin...,NaN
1171,4633016,Manila,OYO 138 White Palace Hotel,"484 Romero Salas Street, Ermita, Ermita, 1000 ...","14.57467000,120.98144600","['Free WiFi Internet Access Included', 'Free P...","['Standard Double Room', 'Deluxe Double Room',...",85 reviews,0.773333,Very good,...,"['Free parking', 'Air conditioning', 'Refriger...",20,$33 - $64 (Based on Average Rates for a Standa...,3 reviews,#20,0.7,Excellent,"{'Cleanliness': 3.0, 'Service': 3.0}",NaN,White Palace Hotel
1172,2563824,Manila,Swiss-Belhotel Blulane,"609 Tomas Mapua Street, Corner Ongpin Street, ...","14.60168878,120.97962571","['Free WiFi Internet Access Included', 'Airpor...","['Superior King Room', 'Deluxe Room', 'King Ro...",64 reviews,0.720000,Good,...,"['Room service', 'Restaurant', 'Bar/Lounge', '...",171,$46 - $62 (Based on Average Rates for a Standa...,14 reviews,#50,0.6,Very good,"{'Location': 3.0, 'Cleanliness': 3.5, 'Service...",NaN,NaN
1173,2514063,Manila,OYO 168 Governor Forbes Inn,"Governor Forbes Inn, 515 A.H. Lacson Avenue co...","14.60549735,120.99655820","['Free WiFi Internet Access Included', 'Free P...","['Deluxe Twin Room', 'Triple Room', 'Quadruple...",167 reviews,0.760000,Very good,...,"['Free parking', 'Restaurant', 'Free High Spee...",33,$16 - $29 (Based on Average Rates for a Standa...,11 reviews,#13,0.7,Very good,"{'Location': 3.5, 'Cleanliness': 3.5, 'Service...",NaN,Governor Forbes Inn

In [19]:
data_attr.to_csv('data_attr.csv')